#
## jekyll params
permalink: /:year/:month/:day/:title.html
paginate: 8
timezone: Asia/Shanghai
excerpt_separator: "\n\n\n\n"


### self params
site_name: 我是疯子
site_description: 在此停留片刻，偶有所得！
url: http://jgj1986.github.io
author: jgj
author_github_url: https://github.com/jgj1986
author_email: jingj1986@gmail.com

## if you don't want something below, just comment it or delete it. But if you want to use, please change your ids.
duoshuo_short_name: blog-woshifengzi
#disqus_shortname: kissdata
#google_analytics_ua: UA-52060953-1
#cnzz_id: 1253396463
kp747_id: e1e0400080105329     ##    http://www.kp747.com



### jekyll params
defaults:
    - 
        scope:
            path: ""
            type: "posts"
        values:
            layout: "page"
            comments: "true"
    -
        scope:
            path: "daily"
        values:
            category: "生活随记"
            
    -
        scope:
            path: "bigdata"
        values:
            category: "bigdata"

    -
        scope:
            path: "web"
        values:
            category: "web"
            
    -
        scope:
            path: "database"
        values:
            category: "database"
            
    -
        scope:
            path: "linux"
        values:
            category: "linux"
            
    -
        scope:
            path: "go"
        values:
            category: "go"
